# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1

# Use Node.js LTS on Alpine
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json tsconfig.node.json ./
COPY src ./src
RUN npm ci --ignore-scripts && npm run build

# Production image
FROM node:lts-alpine AS runner
WORKDIR /app

# Copy build artifacts and dependencies
COPY --from=builder /app/dist ./dist
COPY package.json package-lock.json ./
RUN npm ci --production --ignore-scripts

# Default environment
ENV NODE_ENV=production
EXPOSE 3000

# Start the MCP server
CMD ["node", "dist/server.js"]
